export const Constantes = {
    addUser: '[addUser]',
    removeUser: '[removeUser]',
    updateUser: '[updateUser]',
    loadingUsers: '[loadingUsers]',
    message001: 'Registro creado',
    message002: 'Registro actualizado',
    message003: 'Registro eliminado',
    message004: 'Username y password requeridos',
    message005: 'Username o password invalidos',
    message006: 'No tiene acceso al recurso o permisos',
    messageSuccess: 'success',
    messageWarning: 'warning',
    messageError: 'error',
    login: '[login]',
    logout: '[logout]',
    settingsLogout: 'Logout',
    optionRegisterMenu: 'REGISTRAR',
    optionUsersMenu: 'USUARIOS'
}